- name: My first play
  hosts: my_servers
  vars_files:
    - ../group_vars/vault.yaml
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:

   - name: Print message
     ansible.builtin.debug:
       msg: Hello world